
export const LuxuryCardData = [
    {
      id: 1,
      src:`/7.jpg`,
      title: "Lamborghini Urus ",
      t1:"4 Seats",
      t2:"Auto",
      t3:"2 Bag",
      t4:"Age 25",
      price:"$700",
    },
    {
      id: 2,
      src:`/8.jpg`,
      title: "Aston Martin DBX ",
      t1:"4 Seats",
      t2:"Auto",
      t3:"2 Bag",
      t4:"Age 25",
      price:"$500",
    },
    {
      id: 3,
      src:`/9.jpg`,
      title: "Bugatti Mistral W16 ",
      t1:"2 Seats",
      t2:"Auto",
      t3:"2 Bag",
      t4:"Age 25",
      price:"$800",
    },
    {
      id: 4,
      src:`/bentley.jpg`,
      title: "Bentley Batayga  ",
      t1:"4 Seats",
      t2:"Auto",
      t3:"2 Bag",
      t4:"Age 25",
      price:"$600",
    },
    {
      id: 5,
      src:`/12.jpg`,
      title: "Rolls Royce Cullinan",
      t1:"4 Seats",
      t2:"Auto",
      t3:"4 Bag",
      t4:"Age 25",
      price:"$900",
    },
    {
      id: 6,
      src:`/13.jpg`,
      title: "Bentley Continental ",
      t1:"4 Seats",
      t2:"Auto",
      t3:"2 Bag",
      t4:"Age 25",
      price:"$500",
    },
    {
      id: 7,
      src:`/Red-o.jpg`,
      title: "Audi RS7 SportBack",
      t1:"4 Seats",
      t2:"Auto",
      t3:"2 Bag",
      t4:"Age 25",
      price:"$450",
    },
    {
      id: 8,
      src:`/15.jpg`,
      title: "Audi Q8 ",
      t1:"4 Seats",
      t2:"Auto",
      t3:"3 Bag",
      t4:"Age 25",
      price:"$450",
    },
]