

 export const carDetails = [
  {
    src: '/15.jpg',
    name: 'Audi Q8',
    seats: '4 Seats',
    transmission: 'Auto',
    bags: '3 Bags',
    age: 'Age 25',
    price: '$450',
  },
  {
    src: '/7.jpg',
    name: 'Lamborghini Urus',
    seats: '4 Seats',
    transmission: 'Auto',
    bags: '2 Bags',
    age: 'Age 25',
    price: '$750',
  },
  {
    src: '/8.jpg',
    name: 'Aston Martin DBX',
    seats: '4 Seats',
    transmission: 'Auto',
    bags: '2 Bags',
    age: 'Age 25',
    price: '$500',
  },
  {
    src: '/9.jpg',
    name: 'Bugatti Mistral W16',
    seats: '2 Seats',
    transmission: 'Auto',
    bags: '2 Bags',
    age: 'Age 25',
    price: '$800',
  },
  {
    src: '/bentley.jpg',
    name: 'Bentley Batayga',
    seats: '4 Seats',
    transmission: 'Auto',
    bags: '2 Bags',
    age: 'Age 25',
    price: '$600',
  },
  {
    src: '/12.jpg',
    name: 'Rolls Royce Cullinan',
    seats: '4 Seats',
    transmission: 'Auto',
    bags: '2 Bags',
    age: 'Age 25',
    price: '$900',
  },
  {
    src: '/13.jpg',
    name: 'Bentley Continental',
    seats: '4 Seats',
    transmission: 'Auto',
    bags: '2 Bags',
    age: 'Age 25',
    price: '$500',
  },
  {
    src: '/Red-o.jpg',
    name: 'Audi RS7 SportBack',
    seats: '4 Seats',
    transmission: 'Auto',
    bags: '2 Bags',
    age: 'Age 25',
    price: '$450',
  },
];

 export const carTypes = [
  { src: '/03.jpg', title: 'Luxury Cars' },
  { src: '/04.jpg', title: 'Sport Cars' },
  { src: '/02.jpg', title: 'SUV' },
  { src: '/01.jpg', title: 'Convertible' },
  { src: '/05.jpg', title: 'Sedan' },
  { src: '/06.jpg', title: 'Small Cars' },
];
 export const carNews = [
  { src: '/GreenCar.jpg', title: 'Rental', p:'Document Required for car rental' },
  { src: '/04(1).jpg', title: 'SPORT CARS', p:'Rental cost of sport and other cars' },
  { src: '/05(1).jpg', title: 'FINES', p:'Rental car how to check driving fines?' },
  { src: '/o.jpg', title: 'AIR PORT', p:'How to Rent a Car at the aitport Terminal?' },
  { src: '/01(1).jpg', title: 'RULES', p:'Penalties for violating the ruels in rental cars ' },
  { src: '/bugatti.jpg', title: 'RENTAL Cars', p:'How to check a before reting? ' },
];
// export const LuxuryCarData = [
//     {
//       id: 1,
//       src:`/7.jpg`,
//       title: "Lamborghini Urus ",
//       t1:"4 Seats",
//       t2:"Auto",
//       t3:"2 Bag",
//       t4:"Age 25",
//       price:"$700",
//     },
//     {
//       id: 2,
//       src:`/8.jpg`,
//       title: "Aston Martin DBX ",
//       t1:"4 Seats",
//       t2:"Auto",
//       t3:"2 Bag",
//       t4:"Age 25",
//       price:"$500",
//     },
//     {
//       id: 3,
//       src:`/9.jpg`,
//       title: "Bugatti Mistral W16 ",
//       t1:"2 Seats",
//       t2:"Auto",
//       t3:"2 Bag",
//       t4:"Age 25",
//       price:"$800",
//     },
//     {
//       id: 4,
//       src:`/bentley.jpg`,
//       title: "Bentley Batayga  ",
//       t1:"4 Seats",
//       t2:"Auto",
//       t3:"2 Bag",
//       t4:"Age 25",
//       price:"$600",
//     },
//     {
//       id: 5,
//       src:`/12.jpg`,
//       title: "Rolls Royce Cullinan",
//       t1:"4 Seats",
//       t2:"Auto",
//       t3:"4 Bag",
//       t4:"Age 25",
//       price:"$900",
//     },
//     {
//       id: 6,
//       src:`/13.jpg`,
//       title: "Bentley Continental ",
//       t1:"4 Seats",
//       t2:"Auto",
//       t3:"2 Bag",
//       t4:"Age 25",
//       price:"$500",
//     },
//     {
//       id: 7,
//       src:`/Red-o.jpg`,
//       title: "Audi RS7 SportBack",
//       t1:"4 Seats",
//       t2:"Auto",
//       t3:"2 Bag",
//       t4:"Age 25",
//       price:"$450",
//     },
//     {
//       id: 8,
//       src:`/15.jpg`,
//       title: "Audi Q8 ",
//       t1:"4 Seats",
//       t2:"Auto",
//       t3:"3 Bag",
//       t4:"Age 25",
//       price:"$450",
//     },
// ]

export const carr = [
  { p: '1', title: 'Luxury Cars' },
  { p: '2', title: 'Sport Cars' },
  { p: '3', title: 'SUV' },
  { p: '4', title: 'Convertible' },
  { p: '5', title: 'Sedan' },
  { p: '6', title: 'Small Cars' },
];